spring.application.name=fawatir

## DataSource Config
spring.datasource.url=jdbc:postgresql://localhost:5432/fawatir
spring.datasource.username=postgres
spring.datasource.password=1602

## JPA Config
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.generate-ddl=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.globally_quoted_indentifiers=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.sql.init.mode=never